### ISSUE TITLE
Create Sphinx documentation 

### ISSUE THREAD

**Issue by ConorMacBride** [OpenAstronomy/github-actions-workflows#10]
Move documentation from README to a separate website on readthedocs.

**Comment by ConorMacBride** [comment]
Hi @navaneethkulal8, thank you! 

For some more context, our documentation would be much easier to navigate if each workflow was documented as a separate page on a Sphinx website. This should just be a matter of running [`sphinx-quickstart docs`](https://www.sphinx-doc.org/en/master/usage/quickstart.html) and copying the three sections in `/README.md` to separate `/docs/____.rst` files:
- [Test a Python package using tox](https://github.com/OpenAstronomy/github-actions-workflows/issues/10#test-a-python-package-using-tox)
- [Build and publish a Python package](https://github.com/OpenAstronomy/github-actions-workflows/issues/10#build-and-publish-a-python-package)
- [Build and publish a pure Python package](https://github.com/OpenAstronomy/github-actions-workflows/issues/10#build-and-publish-a-pure-python-package)

**Comment by ConorMacBride** [comment]
@OpenAstronomy/website I have configured RTD to use `github-actions-workflows.openastronomy.org`. Could whoever manages the DNS create a CNAME record for this subdomain that points to `readthedocs.io`? Or would you prefer we use a RTD domain? Thanks

**Comment by Cadair** [comment]
I have added it, may take a little while to trickle through.
