### ISSUE TITLE
Develop a workflow for publishing packages with limited PEP 387 API

### ISSUE THREAD

**Issue by astrofrog** [OpenAstronomy/github-actions-workflows#11]
Packages can use the limited API here: https://docs.python.org/3/c-api/stable.html to avoid having to build wheels for every Python version. It would be nice to investigate whether we can write a workflow that eg builds wheels for the oldest supported Python version and tests it on all the more recent ones.

**Comment by ConorMacBride** [comment]
Do we still need this issue? The `publish.yml` workflow already works with packages configured to use PEP 387 (e.g. https://github.com/astrofrog/fast-histogram/pull/56 and https://github.com/sunpy/sunpy/pull/6171).

**Comment by astrofrog** [comment]
No we can close this! :)
