### ISSUE TITLE
Coverage upload gives 404 even with token

### ISSUE THREAD

**Issue by pllim** [OpenAstronomy/github-actions-workflows#113]
Example log: https://github.com/astropy/astropy/actions/runs/4419131201/jobs/7747176459 (from a pull request https://github.com/astropy/astropy/pull/14319)

How we are using your workflow: https://github.com/astropy/astropy/blob/b6d33e25345e0cabdd58991a7740a1d996b8281c/.github/workflows/ci_workflows.yml#L74-L77

We have CODECOV_TOKEN defined (though technically we do not need it because it is a public repo). Though perhaps the PR cannot see this token?

```
There was an error running the uploader: Error uploading to https://codecov.io
Error: There was an error fetching the storage URL during POST:
404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API.
Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

As a result, the coverage check failed due to incomplete stats.

Is there a solution for this?

**Comment by ConorMacBride** [comment]
Yeah, the issue is that it cannot see the token. Even on `main`, where permissions should not be an issue, it has no token: https://docs.github.com/en/actions/learn-github-actions/variables#using-the-env-context-to-access-environment-variable-values

**Comment by ConorMacBride** [comment]
Astropy needs to pass the secret to the tox workflow like this: https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow

**Comment by pllim** [comment]
Ah, okay. That makes sense. Thanks!

**Comment by ConorMacBride** [comment]
Just realised that will still not make the token accessible in PRs from forks. For security, GitHub doesn't give them access to secrets as they could modify the workflow in their PR to steal the secret.

**Comment by pllim** [comment]
That also makes sense but would be super annoying if we keep getting 404 for no apparent reason.

At least we won't see this 404 after merge?

**Comment by ConorMacBride** [comment]
Yeah, it should work fine after merging. 

How frequent are the 404s? Is it mostly when lots of PR CIs are running at once? I'm surprised it's still an issue.

**Comment by pllim** [comment]
`astropy` is relatively high traffic but I wouldn't say they are excessive. It is frequent enough that some contributors are concerned by the apparent coverage failure.
