### ISSUE TITLE
Not possible to put cibuildwheel test or extras config in pyproject.toml

### ISSUE THREAD

**Issue by dstansby** [OpenAstronomy/github-actions-workflows#126]
Because the publish workflow specifies the follwing environment variables:
https://github.com/OpenAstronomy/github-actions-workflows/blob/bb12d5420b890a2102eea80fbfbda86e626baec4/.github/workflows/publish.yml#L167-L168

it's not possible to instead configure these cibuildwheel options in a `pyproject.toml` file, because not setting these inptus sets the environment variables to empty strings, which overrides `pyproject.toml` configuration.

Possible solutions:
- Only set these environment variables if the inputs are given to the action
- Remove these variables, and instead tell users to use `pyproject.toml` to configure cibuildwheel. This would be breaking, but I think with a major version bump of the action fine.

**Comment by ConorMacBride** [comment]
Similar to #77. I think the first option should be possible. The environment variables can be conditionally set in a new workflow job step just before the cibuildwheel step.

**Comment by Cadair** [comment]
Picking up on https://github.com/OpenAstronomy/github-actions-workflows/pull/127#issuecomment-1519168858 I wonder if we should make the sdist action be able to read its config from pyproject.toml then we wouldn't need these vars at all?
