### ISSUE TITLE
Add support for CIBW_ENVIRONMENT

### ISSUE THREAD

**Issue by pllim** [OpenAstronomy/github-actions-workflows#149]
I need something like this to build wheel for Python 3.12 for packages with C stuff that needs unreleased numpy 1.26b. Unfortunately, I don't know if it is possible from your workflow here. Please help. Thanks!

https://github.com/scipy/scipy/blob/34366e000b3f37732c4254476e0d6df1857f1f70/.github/workflows/wheels.yml#L136C11-L136C27

Related PRs:

* https://github.com/liberfa/pyerfa/pull/111
* https://github.com/astropy/astropy/pull/14784 or https://github.com/astropy/astropy/pull/15202

**Comment by ConorMacBride** [comment]
I think this should already be possible with the [`env` option](https://github-actions-workflows.openastronomy.org/en/latest/publish.html#env). Please let me know if that works

**Comment by pllim** [comment]
Indeed, `env` works. Thanks!

**Comment by pllim** [comment]
So while this works, it also un-discriminatorily pulls down numpy 1.26b for everything, not just the cp312 stuff. This also breaks *all* the `win32` jobs because I guess this new numpy does not ship `win32` wheels no more.

```yaml
      env: |
        CIBW_ENVIRONMENT: PIP_PRE=1
```

What is the best way to tell the workflow to only do it for certain Python version here? Or do I need a totally separate workflow just for cp312.

**Comment by ConorMacBride** [comment]
You could try:
```yaml
env: |
    CIBW_ENVIRONMENT: 'PIP_PRE=$( if [ "${CIBW_BUILD:0:5}" = "cp312" ]; then echo 1; else echo 0; fi )'
```
A neater solution might be to configure [`CIBW_BEFORE_ALL`](https://cibuildwheel.readthedocs.io/en/stable/options/#before-all), either as an env var or in pyproject.yaml. It could call a script that sets env vars.

**Comment by pllim** [comment]
Alas, something isn't quite right in the if-else syntax you provided. The "else" seems to work but "then" failed to assign 1 to the variable. I get this:

```
e476a803-2995-460c-b317-5d3068b425a5.sh: 3: Bad substitution
{
  "CIBW_ENVIRONMENT": "PIP_PRE="
}
...
CIBW_ENVIRONMENT: PIP_PRE=
CIBW_BUILD: cp312-manylinux_x86_64
```
