### ISSUE TITLE
`sdist` not being uploaded along with the wheels.

### ISSUE THREAD

**Issue by WilliamJamieson** [OpenAstronomy/github-actions-workflows#167]
This is related to astropy/astropy#15597.

## Background
The astropy 6.0rc1 release was triggered, which triggered the building and uploading of the astropy 6.0rc1 wheels to PyPi, see https://github.com/astropy/astropy/actions/runs/6817064464/job/18540287448. The issue is that the source distribution was not uploaded to PyPi along side all the pre-built wheels.

It looks like the `Run actions/upload-artifact@v3` step was successfully triggered by all of the wheel builds, see for example https://github.com/astropy/astropy/actions/runs/6817064464/job/18539760549. However, for the source distribution `Run actions/upload-artifact@v3` was not triggered, see https://github.com/astropy/astropy/actions/runs/6817064464/job/18539753723.

As far as I can tell, the source distribution upload would only be blocked by: https://github.com/OpenAstronomy/github-actions-workflows/blob/59a929bdf64d072b19c8fc758ae44dd768f6f3fe/.github/workflows/publish.yml#L235-L236

This appears to be identical to the wheel upload blocker: https://github.com/OpenAstronomy/github-actions-workflows/blob/59a929bdf64d072b19c8fc758ae44dd768f6f3fe/.github/workflows/publish.yml#L193-L194

Yet the former was blocked while the latter was not. Diving into the logs we see that for both the source and wheel builds the inputs both clearly have `upload_to_pypi: true` meaning that in both cases the upload should have occurred, see

- Source: https://github.com/astropy/astropy/actions/runs/6817064464/job/18539753723#step:1:84
- Wheel: https://github.com/astropy/astropy/actions/runs/6817064464/job/18539760549#step:1:84

So I do not understand why one uploads while the other does not. There are no failures in any of the steps proceeding the failure.

**Comment by WilliamJamieson** [comment]
Tagging @ConorMacBride and @Cadair for assistance.

**Comment by astrofrog** [comment]
I've been investigating this but I also don't understand what is going on. Will keep trying, but in the meantime I think it should be safe to upload a locally built sdist.

**Comment by WilliamJamieson** [comment]
The stcal package experienced the same issue (source distribution did not get uploaded to PyPi) today when it made a release. See the https://github.com/spacetelescope/stcal/actions/runs/6881432549/job/18717759512

**Comment by astrofrog** [comment]
Ok I'll try and investigate some more

**Comment by astrofrog** [comment]
Mystery solved: https://github.com/OpenAstronomy/github-actions-workflows/pull/169

**Comment by WilliamJamieson** [comment]
I can confirm that this indeed fixed the issue. `stcal` successfully uploaded everything via the run of: https://github.com/spacetelescope/stcal/actions/runs/6892869688/job/18751126499
see: https://pypi.org/project/stcal/1.5.1/#files for PyPi confirmation.
