### ISSUE TITLE
BUG: cp310*win_amd64 wheels failed with invalid --only

### ISSUE THREAD

**Issue by pllim** [OpenAstronomy/github-actions-workflows#183]
Example log: https://github.com/astropy/astropy/actions/runs/7717116721/job/21035485705

```
Run pipx run --python "C:\hostedtoolcache\windows\Python\3.12.1\x64\python.exe" --spec "D:\a\_actions\pypa\cibuildwheel\v2.16.4" cibuildwheel "." --output-dir '"dist"' --config-file '""' --only '""'
creating virtual environment...
determining package name from 'D:\\a\\_actions\\pypa\\cibuildwheel\\v2.16.4'...
creating virtual environment...
installing cibuildwheel from spec 'D:\\a\\_actions\\pypa\\cibuildwheel\\v2.16.4'...
Invalid --only='""', must be a build selector with a known platform
```

Is this caused by #182 or #144 ?

**Comment by ConorMacBride** [comment]
GitHub upgraded powershell https://github.com/pypa/cibuildwheel/issues/1740 Hopefully fix makes it into a release soon.

**Comment by pllim** [comment]
Thanks for the link!

**Comment by pllim** [comment]
Thanks!

**Comment by pllim** [comment]
Oh wait, I guess this workflow here still needs updating?

https://github.com/OpenAstronomy/github-actions-workflows/blob/36c724caccfa99f52cba2f5a9a3bd052c37857fe/.github/workflows/publish.yml#L186

**Comment by henryiii** [comment]
If you use `uses: pypa/cibuildwheel@v2.16` you are fine, but yes, `uses: pypa/cibuildwheel@v2.16.4` needs to be updated to `uses: pypa/cibuildwheel@v2.16.5`.

**Comment by henryiii** [comment]
(or any older version)
