### ISSUE TITLE
Tag initial version

### ISSUE THREAD

**Issue by astrofrog** [OpenAstronomy/github-actions-workflows#19]
I'd like to start using the publishing workflows in production but before doing that I think it would be good to tag a first version so we can ``@v1`` to avoid any breakages.

Will we just go with semantic versioning and start at 1.0.0? Does ``@v1`` include all ``1.x.x`` releases?

**Comment by ConorMacBride** [comment]
> Will we just go with semantic versioning and start at 1.0.0?

I think so :+1:

> Does @v1 include all 1.x.x releases?

Maybe not because [`actions/upload-artifact`](https://github.com/actions/upload-artifact/tags) for example move the `v_` tag to point to the latest `v_._._`.

**Comment by astrofrog** [comment]
I wonder if there is an existing GitHub action that will do that automatically?

**Comment by astrofrog** [comment]
Ah like this: https://github.com/marketplace/actions/update-major-version

**Comment by astrofrog** [comment]
Yes good point

**Comment by astrofrog** [comment]
Great!

**Comment by astrofrog** [comment]
Should we try and resolve https://github.com/OpenAstronomy/github-actions-workflows/issues/21 as the last point before we tag, since it would be a change of API effectively?

**Comment by astrofrog** [comment]
@ConorMacBride @Cadair - now that #21 is resolved, shall we go ahead and tag a first release here?

**Comment by ConorMacBride** [comment]
Yes :+1:

**Comment by astrofrog** [comment]
@ConorMacBride - would you like to go ahead and do that? I guess we need to add the action for the auto-tagging first?

**Comment by ConorMacBride** [comment]
Okay, I'll add the workflow just like here: https://github.com/ConorMacBride/install-package/blob/main/.github/workflows/update_tag.yml

And then I'll push a `v1.0.0` tag.

**Comment by ConorMacBride** [comment]
Done! 🎉 (Should probably disable PyPI upload in the tests so pushing a tag doesn't fail the tests: https://github.com/OpenAstronomy/github-actions-workflows/runs/5558235131?check_suite_focus=true)

**Comment by Cadair** [comment]
Thanks! Close?
