### ISSUE TITLE
[PROPOSAL 🚀 ] migrate to `uv` for installing python packages

### ISSUE THREAD

**Issue by SauravMaheshkar** [OpenAstronomy/github-actions-workflows#192]
[uv](https://github.com/astral-sh/uv) backed by [Astral](https://astral.sh/), the creators of [Ruff](https://github.com/astral-sh/ruff), is an extremely fast Python package installer and resolver, written in Rust. According to their open-source benchmarks they are [10-100x faster](https://github.com/astral-sh/uv/blob/main/BENCHMARKS.md) than pip and pip-tools (pip-compile and pip-sync).

`uv` has been adopted by popular repositories such as [`diffusers`](https://github.com/huggingface/diffusers) with [observed performance boost](https://x.com/RisingSayak/status/1763037626372632884?s=20).

More than happy to take this up

**Comment by Cadair** [comment]
I believe there's no real need to do this in this repo. While there are a couple of pip commands in the workflow they only install a couple of packages. The real speedups would come from users configuring tox-uv and having tox use uv. As this is already possible, perhaps the only thing to do is mention it in the docs?

**Comment by SauravMaheshkar** [comment]
> I believe there's no real need to do this in this repo. While there are a couple of pip commands in the workflow they only install a couple of packages. The real speedups would come from users configuring tox-uv and having tox use uv. As this is already possible, perhaps the only thing to do is mention it in the docs?

Thanks for the feedback, which part of the docs do you think would be best for this?

**Comment by astrofrog** [comment]
Looking into this a bit I think the easiest way to achieve this would be to install tox-uv at the same time as tox, which is something that could be done in the workflows. Maybe we could have an option for the tox workflow to install tox-uv?

**Comment by Cadair** [comment]
We already have the [`toxdeps:`](https://github-actions-workflows.openastronomy.org/en/latest/tox.html#toxdeps) argument which lets you do that, so we don't need to do anything people just need to add `toxdeps: tox-uv` to any runs they want to use uv. Maybe putting an example under the `toxdeps` section of the docs is the best place? either that or adding a new FAQ section?

**Comment by astrofrog** [comment]
Sounds good!

**Comment by SauravMaheshkar** [comment]
I was thinking of adding some text to: 

https://github.com/OpenAstronomy/github-actions-workflows/blob/77f4c83f8595003f7842bcff4d2c5ebb82b4aacd/docs/source/tox.rst#toxdeps

**Comment by Cadair** [comment]
@SauravMaheshkar that would be good, doesn't need to be much and should be phrased as an example of a general way to install tox plugins.
