### ISSUE TITLE
install packages on macOS in `publish.yml`

### ISSUE THREAD

**Issue by zacharyburnett** [OpenAstronomy/github-actions-workflows#201]
https://github.com/spacetelescope/romanisim/pull/121#issuecomment-2098627449

When attempting to run `publish.yml`, the build fails due to not having requisite libraries:
https://github.com/spacetelescope/romanisim/actions/runs/8973449274/job/24643649477?pr=121#step:7:1002
```
Could not find an installed fftw3 library named libfftw3.dylib
```

I can use the following in `tox.yml`, but it does not appear to work the same in `publish.yml`:
```yaml
libraries: |
  brew: 
    - fftw
```

Is this possible with the QEMU emulator? (I'm not entirely sure how the build workflow works)

**Comment by astrofrog** [comment]
I think you will need to use cibuildwheel's options to achieve this - can take a look later this week if needed

**Comment by zacharyburnett** [comment]
it looks like we can set [`CIBW_BEFORE_BUILD`](https://cibuildwheel.pypa.io/en/stable/options/#before-build) to something like `brew install fftw`; I'll have to see if the environment has `brew` available

**Comment by astrofrog** [comment]
@zacharyburnett - yes that's the correct environment variable. You can also use a pyproject.toml setting if you prefer. I think the MacOS images should include ``brew`` since it should just use GitHub Actions (which does have ``brew``)

**Comment by zacharyburnett** [comment]
thank you! I added some documentation in #202 to explain that, for anyone in my situation in the future
