### ISSUE TITLE
Clean up workflow file path

### ISSUE THREAD

**Issue by Cadair** [OpenAstronomy/github-actions-workflows#21]
Is there a way we can change this:

```
uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@main
```

into this:
```
uses: OpenAstronomy/github-actions-workflows/tox.yml@main
```

Having the `.github` in particular is ugly, but also just making this shorter is going to make things better for a lot of downstreams.

**Comment by ConorMacBride** [comment]
[This section of the docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow) suggests that they should be in `.github/workflows`, however [in this section](https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow) they give `{owner}/{repo}/{path}/{filename}@{ref}` which seems to suggest that `{path}` can be anything. Might need to test and see.

**Comment by ConorMacBride** [comment]
This is not possible because [references to workflows must be rooted in '.github/workflows'](https://github.com/OpenAstronomy/github-actions-workflows/actions/runs/1987563541/workflow). Close?
