### ISSUE TITLE
Provide a way to exclude tags from PyPI upload

### ISSUE THREAD

**Issue by Cadair** [OpenAstronomy/github-actions-workflows#24]
On my [dkist package](https://github.com/DKISTDC/dkist/blob/5de62642ac14c60d979b566174ca481c99f1edee/.github/workflows/publish.yml#L9-L11) I exclude `.dev` tags (as I tag on main, no feature branches yet).

Should we make this easier to config? At the moment it looks like I have to override [`UPLOAD_TAG`](https://github.com/OpenAstronomy/github-actions-workflows/blob/main/.github/workflows/publish_pure_python.yml#L72)?

**Comment by astrofrog** [comment]
You can use upload_to_pypi to have a custom condition I think

**Comment by ConorMacBride** [comment]
Yes, you can use a custom condition.
```yaml
upload_to_pypi: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') && !endsWith(github.event.ref, '.dev') }}
```
