### ISSUE TITLE
Coverage arguments are broken on windows

### ISSUE THREAD

**Issue by Cadair** [OpenAstronomy/github-actions-workflows#25]
I don't quite understand this but the coverage.xml path computation isn't working on windows.

We are going from this: https://github.com/DKISTDC/dkist/runs/5568366657?check_suite_focus=true#step:8:1 where the path looks ok to this: https://github.com/DKISTDC/dkist/runs/5568366657?check_suite_focus=true#step:8:15 where it isn't. Do we need an extra `\` here: https://github.com/OpenAstronomy/github-actions-workflows/blob/main/tools/tox_matrix.py#L117 or something?

**Comment by ConorMacBride** [comment]
Hmm, I thought there was already an extra slash. Maybe it should be `r"\\"` instead of `"\\"`?
