### ISSUE TITLE
Transient failures when using workflows

### ISSUE THREAD

**Issue by astrofrog** [OpenAstronomy/github-actions-workflows#34]
I am starting to see an issue in both the glue-viz and astropy organization where - I think - when GitHub actions is quite busy for the organization, the workflow build will fail complaining about not finding a self-hosted runner:

![Screenshot from 2022-03-31 14-30-16](https://user-images.githubusercontent.com/314716/161067692-4adc86b9-6499-4987-ac3e-fe6c216793f6.png)

**Comment by ConorMacBride** [comment]
This should now be fixed: https://github.community/t/called-workflows-cannot-be-queued-onto-self-hosted-runners-across-organisations-enterprises-failed-to-queue-this-job-labels-ubuntu-latest/229355/16
