### ISSUE TITLE
Allow a list of environment variables to be passed publish workflows

### ISSUE THREAD

**Issue by ConorMacBride** [OpenAstronomy/github-actions-workflows#52]
["Any environment variables set in an env context defined at the workflow level in the caller workflow are not propagated to the called workflow."](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations) A new input for `publish.yml` and `publish_pure_python.yml` should be added which accepts a YAML list of environment variable names and values (encoded as a multiline string). Each of the build steps of both publishing workflows should call a Python script which parses the YAML input and [writes each environment variable to the file defined by `GITHUB_ENV`](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable).

**Comment by nabobalis** [comment]
Am I misunderstanding this:

If I define a env at the top of an actions file, it will not be passed to any publish step?

**Comment by ConorMacBride** [comment]
That's correct

**Comment by nabobalis** [comment]
> That's correct

😭 All this time, I thought it was my CI script.

**Comment by nabobalis** [comment]
Thank you @ConorMacBride for working on this
