### ISSUE TITLE
Upload coverage to codecov, even if some tests fail

### ISSUE THREAD

**Issue by dstansby** [OpenAstronomy/github-actions-workflows#81]
In sunpy we often have remote data tests failing because of remote data provider issues. In this case we often merge PRs with failing tests, but want the code coverage to be measured on the remote data runs that have some failing tests. It would therefore be good to uplaod code coverage even if some tests fail.

**Comment by Cadair** [comment]
It looks like this is something that you can configure directly with codecov: https://docs.codecov.com/docs/common-recipe-list#see-coverage-on-ci-test-failures

**Comment by ConorMacBride** [comment]
The codecov config doesn't control whether results are uploaded, just how the report is presented. We would need to add an ["if: always"](https://docs.github.com/en/actions/learn-github-actions/expressions#always) to the upload step, but that may not be wanted in most cases.

**Comment by Cadair** [comment]
Ah, I see.
