### ISSUE TITLE
Please pin tox<4

### ISSUE THREAD

**Issue by pllim** [OpenAstronomy/github-actions-workflows#93]
So I can move on with my life... 🙏 

xref

* https://github.com/tox-dev/tox/issues/2612
* https://github.com/astropy/astropy/pull/14139

**Comment by Cadair** [comment]
I don't want to do this as you can override the default behaviour with the toxdeps matrix variable: https://github.com/OpenAstronomy/github-actions-workflows/#toxdeps

**Comment by pllim** [comment]
I wouldn't know what kind of syntax it takes from that link. What is example?

**Comment by pllim** [comment]
Not as straight forward as it seems. Had to try a few times at https://github.com/astropy/astropy/pull/14142

**Comment by pllim** [comment]
I cannot get it to work downstream.

`Run python -m pip install --upgrade tox <'4'`

**Comment by Cadair** [comment]
This has been fixed downstream.

**Comment by pllim** [comment]
Some doc here would still be nice, if not done already. Thanks!
